# Generated by Django 2.0.5 on 2018-06-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180615_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='likes',
        ),
    ]
