# Generated by Django 2.0.5 on 2018-06-15 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20180615_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
