# Generated by Django 2.0.5 on 2018-06-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_userpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_body',
            field=models.TextField(blank=True, default='Whats happening?', null=True),
        ),
    ]
